server:
  port: 8007
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false

logging:
  level:
    com.netflix: DEBUG

zuul:
  AccessFilter:
    pre:
      disable: true







