server:
  port: 8007
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
zuul:
  ignored-services: '*'
  routes:
    ribbon-route:
      #url: http://localhost:8003/
      service-id: ribbon-demo
      path: /ribbon/**
logging:
  level:
    com.netflix: DEBUG







